### ISSUE TITLE
The experiment results cannot be reproduced.

### ISSUE THREAD

**Issue by gczzcc** [JiehongLin/Self-DPDN#12]
Hello, I read the article you published, and I think your ideas are excellent. However, when I tried to reproduce your experimental results using the 'DPDN-Pytorch1.9.0-Cuda11.2' code you provided, I encountered some issues. I used the same experimental settings and dataset as you, but the accuracy of the model I trained never reached the required level. Here are my training logs and evaluation results：
train_log:
023-12-07 15:05:16,044 - ************************ Start Logging ************************
2023-12-07 15:08:25,106 - ************************ Start Logging ************************
2023-12-07 15:08:32,280 - #Total parameters : 180209279
2023-12-07 16:51:25,890 - Epoch 1 - train_time(min): 102.88154	train_loss_all: 2.60435	train_loss_syn: 2.41283	train_loss_real: 0.19152	
2023-12-07 17:08:00,579 - ************************ Start Logging ************************
2023-12-07 17:08:07,988 - #Total parameters : 180209279
2023-12-07 18:46:49,464 - Epoch 1 - train_time(min): 98.44879	train_loss_all: 2.46578	train_loss_syn: 2.28685	train_loss_real: 0.17893	
2023-12-07 20:31:16,272 - Epoch 2 - train_time(min): 104.44630	train_loss_all: 1.46470	train_loss_syn: 1.36545	train_loss_real: 0.09925	
2023-12-07 22:16:11,884 - Epoch 3 - train_time(min): 104.92605	train_loss_all: 1.20643	train_loss_syn: 1.13646	train_loss_real: 0.06997	
2023-12-08 00:00:03,190 - Epoch 4 - train_time(min): 103.85472	train_loss_all: 1.10961	train_loss_syn: 1.04734	train_loss_real: 0.06227	
2023-12-08 01:43:41,693 - Epoch 5 - train_time(min): 103.63348	train_loss_all: 1.13265	train_loss_syn: 1.06578	train_loss_real: 0.06687	
2023-12-08 03:27:29,752 - Epoch 6 - train_time(min): 103.80072	train_loss_all: 1.02380	train_loss_syn: 0.96603	train_loss_real: 0.05777	
2023-12-08 05:11:32,636 - Epoch 7 - train_time(min): 104.04772	train_loss_all: 0.89500	train_loss_syn: 0.84900	train_loss_real: 0.04600	
2023-12-08 06:56:02,467 - Epoch 8 - train_time(min): 104.49684	train_loss_all: 0.76964	train_loss_syn: 0.73406	train_loss_real: 0.03557	
2023-12-08 08:39:56,841 - Epoch 9 - train_time(min): 103.90598	train_loss_all: 0.69508	train_loss_syn: 0.66695	train_loss_real: 0.02813	
2023-12-08 10:26:46,165 - Epoch 10 - train_time(min): 106.81434	train_loss_all: 0.62530	train_loss_syn: 0.60191	train_loss_real: 0.02339	
2023-12-08 12:02:16,649 - Epoch 11 - train_time(min): 95.50766	train_loss_all: 0.61219	train_loss_syn: 0.59017	train_loss_real: 0.02202	
2023-12-08 13:38:04,593 - Epoch 12 - train_time(min): 95.79874	train_loss_all: 0.63726	train_loss_syn: 0.61352	train_loss_real: 0.02374	
2023-12-08 15:13:43,988 - Epoch 13 - train_time(min): 95.65566	train_loss_all: 0.66249	train_loss_syn: 0.63621	train_loss_real: 0.02629	
2023-12-08 16:52:23,735 - Epoch 14 - train_time(min): 98.66208	train_loss_all: 0.71813	train_loss_syn: 0.68880	train_loss_real: 0.02934	
2023-12-08 18:31:33,332 - Epoch 15 - train_time(min): 99.15229	train_loss_all: 0.74555	train_loss_syn: 0.71476	train_loss_real: 0.03079	
2023-12-08 20:10:53,381 - Epoch 16 - train_time(min): 99.33386	train_loss_all: 0.70756	train_loss_syn: 0.67979	train_loss_real: 0.02777	
2023-12-08 21:50:41,258 - Epoch 17 - train_time(min): 99.79768	train_loss_all: 0.66620	train_loss_syn: 0.63926	train_loss_real: 0.02694	
2023-12-08 23:30:42,780 - Epoch 18 - train_time(min): 100.02513	train_loss_all: 0.60538	train_loss_syn: 0.58429	train_loss_real: 0.02109	
2023-12-09 01:10:26,388 - Epoch 19 - train_time(min): 99.72646	train_loss_all: 0.55363	train_loss_syn: 0.53657	train_loss_real: 0.01705	
2023-12-09 02:49:52,468 - Epoch 20 - train_time(min): 99.42673	train_loss_all: 0.51230	train_loss_syn: 0.49768	train_loss_real: 0.01463	
2023-12-09 04:29:09,710 - Epoch 21 - train_time(min): 99.28650	train_loss_all: 0.50662	train_loss_syn: 0.49215	train_loss_real: 0.01447	
2023-12-09 06:08:09,507 - Epoch 22 - train_time(min): 98.99631	train_loss_all: 0.52653	train_loss_syn: 0.51073	train_loss_real: 0.01580	
2023-12-09 07:47:08,635 - Epoch 23 - train_time(min): 98.98511	train_loss_all: 0.56124	train_loss_syn: 0.54126	train_loss_real: 0.01999	
2023-12-09 09:25:51,432 - Epoch 24 - train_time(min): 98.71283	train_loss_all: 0.57998	train_loss_syn: 0.56003	train_loss_real: 0.01995	
2023-12-09 11:04:22,022 - Epoch 25 - train_time(min): 98.50154	train_loss_all: 0.62380	train_loss_syn: 0.60119	train_loss_real: 0.02262	
2023-12-09 12:42:50,785 - Epoch 26 - train_time(min): 98.47908	train_loss_all: 0.63840	train_loss_syn: 0.61592	train_loss_real: 0.02248	
2023-12-09 14:21:04,096 - Epoch 27 - train_time(min): 98.22159	train_loss_all: 0.57246	train_loss_syn: 0.55320	train_loss_real: 0.01926	
2023-12-09 15:59:41,307 - Epoch 28 - train_time(min): 98.61992	train_loss_all: 0.53996	train_loss_syn: 0.52366	train_loss_real: 0.01630	
2023-12-09 17:38:19,513 - Epoch 29 - train_time(min): 98.63630	train_loss_all: 0.49592	train_loss_syn: 0.48197	train_loss_real: 0.01395	
2023-12-09 19:17:15,264 - Epoch 30 - train_time(min): 98.92149	train_loss_all: 0.46751	train_loss_syn: 0.45525	train_loss_real: 0.01226
test_log:
2023-12-11 10:17:16,240 - ************************ Start Logging ************************
2023-12-11 10:21:20,535 - 3D IoU at 25: 72.2
2023-12-11 10:21:20,555 - 3D IoU at 50: 54.9
2023-12-11 10:21:20,555 - 3D IoU at 75: 37.9
2023-12-11 10:21:20,555 - 5 degree, 2cm: 26.2
2023-12-11 10:21:20,555 - 5 degree, 5cm: 28.0
2023-12-11 10:21:20,555 - 10 degree, 2cm: 44.4
2023-12-11 10:21:20,555 - 10 degree, 5cm: 46.9
I tried changing the PyTorch version, but it didn't solve the problem.
Can you provide any suggestions for me

**Comment by pppkkk611** [comment]
when i run python train.py --gpus 0 --config config/unsupervised.yaml, i meet this problem and don't know how to fix it
(DPDN) PS D:\pppkkk\Self-DPDN-main> python train.py --gpus 0 --config config/unsupervised.yaml
set CUDA_VISIBLE_DEVICES as 0
2024-01-10 17:54:49,286 - ************************ Start Logging ************************
2024-01-10 17:54:49,286 - Config (path: config/unsupervised.yaml)
{
"setting": "unsupervised",
"optimizer": {
"type": "Adam",
"lr": 0.01,
"betas": [
0.5,
0.999
],
"eps": 1e-06,
"weight_decay": 0
},
"lr_scheduler": {
"type": "StepLR",
"step_size": 1,
"gamma": 0.5
},
"bn": {
"bn_momentum": 0.9,
"bn_decay": 0.5,
"decay_step": 4000,
"bnm_clip": 0.01
},
"max_epoch": 30,
"num_mini_batch_per_epoch": 4000,
"num_category": 6,
"num_prior": 1024,
"loss": {
"gamma1": 5.0,
"gamma2": 1.0,
"lambda1": 0.2,
"lambda2": 0.02,
"beta1": 5.0,
"beta2": 1.0
},
"train_dataset": {
"img_size": 192,
"sample_num": 1024,
"shift_range": 0.01
},
"train_dataloader": {
"syn_bs": 18,
"real_bs": 6,
"num_workers": 0,
"shuffle": true,
"drop_last": true,
"pin_memory": false
},
"test": {
"img_size": 192,
"sample_num": 1024
},
"rd_seed": 1,
"per_val": 10,
"per_write": 50,
"exp_name": "unsupervised",
"log_dir": "log\unsupervised",
"gpus": "0",
"checkpoint_epoch": -1
}
2024-01-10 17:54:49,288 - using gpu: 0
2024-01-10 17:54:49,289 - => creating model ...
loading pretrained mdl.
2024-01-10 17:54:49,775 - #Total parameters : 180209279
1010 images found.
1083 models loaded.
796 images found.
18 models loaded.
Traceback (most recent call last):
File "train.py", line 151, in
start_iter=start_iter)
File "D:\pyh\Self-DPDN-main\utils\solver.py", line 38, in init
step_size=cfg.max_epoch * cfg.num_mini_batch_per_epoch // 6, mode='triangular')
File "D:\pyh\Self-DPDN-main\utils\scheduler.py", line 242, in init
super().init(optimizer)
File "C:\Users\user.conda\envs\DPDN\lib\site-packages\torch\optim\lr_scheduler.py", line 77, in init
self.step()
TypeError: step() missing 1 required positional argument: 'step'

**Comment by JiehongLin** [comment]
Sorry, I attempted to locate my log, but it couldn't be found. 

You might first evaluate our checkpoint using the evaluation codes to ensure there are no issues, and then compare the losses between the two checkpoints.

**Comment by gczzcc** [comment]
Hello, I am attempting to evaluate the loss function using the checkpoints you provided, but the loss values show little difference compared to those of my trained model. Additionally, when testing models with different loss function values, it seems that there is little correlation between the loss function and the test accuracy. Could you provide any advice on this matter?

**Comment by JiehongLin** [comment]
Did you conduct tests on both our checkpoint and yours using the same evaluation code? If there's a significant performance gap between them, you may train the model in a completely supervised manner to minimize the impact of the domain gap. If the performance of the supervised model is still subpar, please verify the consistency in environments, configurations, and data processing.

**Comment by gczzcc** [comment]
The training results in a fully supervised setting are excellent and closely match your results. However, the training performance in the self-supervised setting is causing me considerable confusion. I have tried changing the PyTorch version and increasing the number of training epochs to the best of my ability, but the improvement has been minimal.

**Comment by JiehongLin** [comment]
It seems to be a little strange and I am uncertain. Kindly allow me a few days to retrain the model and provide the log for your reference.

**Comment by gczzcc** [comment]
Thank you for your hard work. I really appreciate the help from the expert. The paper and code are excellent.

**Comment by JiehongLin** [comment]
Hi, here is the log of the retrained model that acheves similar results to those mentioned in the paper:

2024-01-12 09:29:13,344 - ************************ Start Logging ************************
2024-01-12 09:29:18,897 - #Total parameters : 204770569
2024-01-12 10:58:59,818 - Epoch 1 - train_time(min): 89.65593	train_loss_all: 2.46113	train_loss_syn: 2.27871	train_loss_real: 0.18241	
2024-01-12 12:07:24,651 - Epoch 2 - train_time(min): 68.41389	train_loss_all: 1.48915	train_loss_syn: 1.38982	train_loss_real: 0.09933	
2024-01-12 13:02:33,285 - Epoch 3 - train_time(min): 55.14389	train_loss_all: 1.23572	train_loss_syn: 1.16054	train_loss_real: 0.07518	
2024-01-12 13:51:24,720 - Epoch 4 - train_time(min): 48.85724	train_loss_all: 1.22494	train_loss_syn: 1.14994	train_loss_real: 0.07500	
2024-01-12 14:37:47,637 - Epoch 5 - train_time(min): 46.32507	train_loss_all: 1.12701	train_loss_syn: 1.05680	train_loss_real: 0.07020	
2024-01-12 15:27:01,787 - Epoch 6 - train_time(min): 49.23583	train_loss_all: 1.04728	train_loss_syn: 0.98132	train_loss_real: 0.06596	
2024-01-12 16:17:34,113 - Epoch 7 - train_time(min): 50.53873	train_loss_all: 0.90020	train_loss_syn: 0.84705	train_loss_real: 0.05315	
2024-01-12 17:06:38,861 - Epoch 8 - train_time(min): 49.07908	train_loss_all: 0.77569	train_loss_syn: 0.73317	train_loss_real: 0.04252	
2024-01-12 17:53:43,241 - Epoch 9 - train_time(min): 47.07299	train_loss_all: 0.70115	train_loss_syn: 0.66536	train_loss_real: 0.03579	
2024-01-12 18:43:17,692 - Epoch 10 - train_time(min): 49.52101	train_loss_all: 0.64073	train_loss_syn: 0.60995	train_loss_real: 0.03078	
2024-01-12 19:32:00,534 - Epoch 11 - train_time(min): 48.71401	train_loss_all: 0.62937	train_loss_syn: 0.59941	train_loss_real: 0.02996	
2024-01-12 20:23:35,804 - Epoch 12 - train_time(min): 51.58782	train_loss_all: 0.65138	train_loss_syn: 0.61887	train_loss_real: 0.03252	
2024-01-12 21:08:58,524 - Epoch 13 - train_time(min): 45.37864	train_loss_all: 0.69338	train_loss_syn: 0.65740	train_loss_real: 0.03598	
2024-01-12 21:51:59,816 - Epoch 14 - train_time(min): 43.02153	train_loss_all: 0.73825	train_loss_syn: 0.69864	train_loss_real: 0.03962	
2024-01-12 22:39:58,090 - Epoch 15 - train_time(min): 47.91836	train_loss_all: 0.81443	train_loss_syn: 0.76881	train_loss_real: 0.04562	
2024-01-12 23:25:22,712 - Epoch 16 - train_time(min): 45.41036	train_loss_all: 0.76412	train_loss_syn: 0.72202	train_loss_real: 0.04210	
2024-01-13 00:09:29,950 - Epoch 17 - train_time(min): 44.12062	train_loss_all: 0.69545	train_loss_syn: 0.65842	train_loss_real: 0.03703	
2024-01-13 00:55:48,989 - Epoch 18 - train_time(min): 46.31732	train_loss_all: 0.62805	train_loss_syn: 0.59717	train_loss_real: 0.03088	
2024-01-13 01:40:25,271 - Epoch 19 - train_time(min): 44.60468	train_loss_all: 0.58014	train_loss_syn: 0.55311	train_loss_real: 0.02703	
2024-01-13 02:24:51,064 - Epoch 20 - train_time(min): 44.37396	train_loss_all: 0.53381	train_loss_syn: 0.51053	train_loss_real: 0.02328	
2024-01-13 03:11:23,700 - Epoch 21 - train_time(min): 46.54391	train_loss_all: 0.52917	train_loss_syn: 0.50658	train_loss_real: 0.02259	
2024-01-13 03:59:09,493 - Epoch 22 - train_time(min): 47.76319	train_loss_all: 0.55631	train_loss_syn: 0.53132	train_loss_real: 0.02499	
2024-01-13 04:47:06,356 - Epoch 23 - train_time(min): 47.94769	train_loss_all: 0.57752	train_loss_syn: 0.55025	train_loss_real: 0.02727	
2024-01-13 05:31:37,515 - Epoch 24 - train_time(min): 44.51931	train_loss_all: 0.61322	train_loss_syn: 0.58306	train_loss_real: 0.03016	
2024-01-13 06:19:45,882 - Epoch 25 - train_time(min): 48.08075	train_loss_all: 0.63954	train_loss_syn: 0.60732	train_loss_real: 0.03222	
2024-01-13 07:09:41,127 - Epoch 26 - train_time(min): 49.92075	train_loss_all: 0.68398	train_loss_syn: 0.64842	train_loss_real: 0.03556	
2024-01-13 07:57:55,731 - Epoch 27 - train_time(min): 48.24339	train_loss_all: 0.64038	train_loss_syn: 0.60826	train_loss_real: 0.03212	
2024-01-13 08:44:40,539 - Epoch 28 - train_time(min): 46.74678	train_loss_all: 0.57831	train_loss_syn: 0.55134	train_loss_real: 0.02697	
2024-01-13 09:31:42,783 - Epoch 29 - train_time(min): 47.03737	train_loss_all: 0.52743	train_loss_syn: 0.50406	train_loss_real: 0.02337	
2024-01-13 10:19:35,847 - Epoch 30 - train_time(min): 47.83039	train_loss_all: 0.49321	train_loss_syn: 0.47254	train_loss_real: 0.02066

**Comment by JiehongLin** [comment]
These are the configurations:

![image](https://github.com/JiehongLin/Self-DPDN/assets/22855829/6048fef5-f3d9-4e90-98ef-0d11385fdc25)
