### ISSUE TITLE
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

### ISSUE THREAD

**Issue by 605521553** [JiehongLin/Self-DPDN#7]
the code uses the version pip install gorilla-core==0.2.5.6
but this version has missed,when i run other version,errors come here.
i cant import gorilla,could you help me to solve it?
Traceback (most recent call last):
  File "/home/scj/IST-Net-main/test.py", line 8, in <module>
    import gorilla
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/__init__.py", line 5, in <module>
    from .utils import *
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/utils/__init__.py", line 5, in <module>
    from .gpu import (get_free_gpu, subprocess, set_cuda_visible_devices)
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gorilla/utils/gpu.py", line 13, in <module>
    from gpustat import GPUStatCollection
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/home/scj/anaconda3/envs/istnet/lib/python3.6/site-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

Process finished with exit code 1

**Comment by JiehongLin** [comment]
You may try `pip install gpustat==1.0.0`.
